import { Poppins } from 'next/font/google'
import './globals.css'

const pop = Poppins({ weight: '500',subsets: ['latin'] })

export const metadata = {
  title: 'CarsAI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="globals.css"></link>
      </head>
      <body className={pop.className}>
        {children}</body>
    </html>
  )
}
