import '../globals.css'


export const metadata = {
title: 'Dashboard',
description: 'Generated by create next app',
}

export default function Dashlayout({ children }) {
return (
    <>
        {children}
    </>
)
}