import { Inter } from 'next/font/google'
import '../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
title: 'Dashboard',
description: 'Generated by create next app',
}

export default function Dashlayout() {
return (
    <section>
        <h1>Dashboard</h1>
    </section>
)
}