import '../globals.css'
import Sidebar from "@/components/dashpage/sidebar"

export const metadata = {
title: 'Dashboard - CarsAI',
description: 'Generated by create next app',
icons: {
    icon: '/images/dashicon.ico'
}
}

export default function Dashlayout({ children }) {
return (
    <>
    <div className='fixed bottom-0'>
        <Sidebar />
    </div>
    <div className='flex h-screen ml-64'>
        {children}
    </div>
    </>
)
}